version: '1'

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - recipereaper-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: recipes
    secrets:
      - db_password
    networks:
      - recipereaper

  scraper:
    image: mhackmann18/recipereaper-scraper
    volumes:
      - /etc/pki:/etc/pki
    ports:
      - 8000:8000
    networks:
      - recipereaper

  api:
    image: mhackmann18/recipereaper-api
    ports:
      - 8080:8080
    networks:
      - recipereaper
    environment:
      PORT: 8080
      CORS_ORIGIN: 'https://www.recipereaper.com'
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      ACCESS_TOKEN_EXPIRES_IN: 3600
      NODE_ENV: production
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DB: recipes
      ADMIN_USERNAME: god_of_prepmaster
      SSL_KEY_FILE: /run/secrets/ssl_key 
      SSL_CERT_FILE: /run/secrets/ssl_cert
    secrets:
      - jwt_secret
      - db_password
      - ssl_key
      - ssl_cert
    depends_on:
      - db

  site:
    image: mhackmann18/recipereaper-site
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/pki:/etc/pki
    networks:
      - recipereaper

networks:
  recipereaper:
    driver: bridge

secrets:
  db_password:
    file: db_password.txt
  jwt_secret:
    file: jwt_secret.txt
  ssl_key:
    file: /etc/pki/tls/private/custom.key
  ssl_cert:
    file: /etc/pki/tls/private/cert.crt

volumes:
  recipereaper-data:
