version: '1'

services:
  db:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - recipereaper-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ds89mg31
      MYSQL_DATABASE: recipes
    networks:
      - recipereaper

  api:
    image: recipereaper-api
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./api/app:/app/app
    networks:
      - recipereaper
    depends_on:
      - db

  site:
    image: recipereaper-site
    ports: 
      - 127.0.0.1:3000:3000
    volumes: 
      - ./site/src:/app/src
    networks: 
      - recipereaper

networks:
  recipereaper:
    external: true

volumes:
  recipereaper-data:
