version: '1'

services:
  db:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - recipereaper-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: recipes
    secrets:
      - db_password
    networks:
      - recipereaper

  scraper:
    image: recipereaper-scraper
    build:
      context: ./scraper
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    networks:
      - recipereaper

  api:
    image: recipereaper-api
    ports:
      - 8080:8080
    volumes:
      - ./api/app:/app/app
    networks:
      - recipereaper
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      PORT: 8080
      CORS_ORIGIN: 'https://www.recipereaper.com'
      KILL: site
      KILL_ALL: scraper
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      ACCESS_TOKEN_EXPIRES_IN: 3600
      NODE_ENV: production
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DB: recipes
      ADMIN_USERNAME: god_of_prepmaster
      SSL_KEY_FILE: /run/secrets/ssl_key
      SSL_CERT_FILE: /run/secrets/ssl_cert
    secrets:
      - jwt_secret
      - db_password
    depends_on:
      - db

  site:
    image: recipereaper-site
    ports: 
      - 80:3000
    volumes: 
      - ./site/src:/app/src
    networks: 
      - recipereaper
    build: 
      context: ./site
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_DOMAIN: recipereaper.com
      REACT_APP_API_ORIGIN: https://www.recipereaper.com:8080
      REACT_APP_SCRAPER_ORIGIN: https://www.recipereaper.com:8000

networks:
  recipereaper:

secrets:
  db_password:
    file: db_password.txt
  jwt_secret:
    file: jwt_secret.txt
  ssl_key:
    file: /etc/pki/tls/private/custom.key
  ssl_cert:
    file: /etc/pki/tls/private/cert.crt

volumes:
  recipereaper-data:
