FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install gunicorn
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8000

# CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8000"]
CMD ["gunicorn", "-b", "0.0.0.0:8000", "--keyfile", "/etc/pki/tls/private/custom.key", "--certfile", "/etc/pki/tls/private/cert.crt", "-w", "2", "app:app"]
